### PR TITLE
Fix `RingBuffer::extend_from_within_unchecked` unsoundness

### LINKED ISSUE #75: Undefined behavior during decoding
Tried to use this crate as an alternative to the zstd crate, to allow tests running with miri, but it crashed due to UB:
```
test test::my_test ... error: Undefined Behavior: using uninitialized data, but this operation requires initialized memory
   --> /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/decoding/ringbuffer.rs:462:30
    |
462 |             .write_unaligned(src.0.cast::<CopyType>().read_unaligned())
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ using uninitialized data, but this operation requires initialized memory
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE on thread `test::my_test`:
    = note: inside `ruzstd::decoding::ringbuffer::copy_bytes_overshooting` at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/decoding/ringbuffer.rs:462:30: 462:71
    = note: inside `ruzstd::decoding::ringbuffer::RingBuffer::extend_from_within_unchecked` at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/decoding/ringbuffer.rs:307:17: 307:62
    = note: inside `ruzstd::decoding::decodebuffer::DecodeBuffer::repeat_in_chunks` at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/decoding/decodebuffer.rs:153:17: 154:72
    = note: inside `ruzstd::decoding::decodebuffer::DecodeBuffer::repeat` at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/decoding/decodebuffer.rs:108:17: 108:71
    = note: inside `ruzstd::decoding::sequence_execution::execute_sequences` at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/decoding/sequence_execution.rs:75:13: 77:65
    = note: inside `ruzstd::decoding::block_decoder::BlockDecoder::decompress_block::<&mut &mut &[u8]>` at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/decoding/block_decoder.rs:448:13: 448:41
    = note: inside `ruzstd::decoding::block_decoder::BlockDecoder::decode_block_content::<&mut &mut &[u8]>` at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/decoding/block_decoder.rs:354:17: 354:65
    = note: inside `ruzstd::frame_decoder::FrameDecoder::decode_blocks::<&mut &[u8]>` at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/frame_decoder.rs:416:44: 417:94
    = note: inside `<ruzstd::streaming_decoder::StreamingDecoder<&[u8], ruzstd::frame_decoder::FrameDecoder> as std::io::Read>::read` at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruzstd-0.7.2/src/streaming_decoder.rs:116:19: 119:14
    = note: inside `std::io::default_read_to_end::small_probe_read::<ruzstd::streaming_decoder::StreamingDecoder<&[u8], ruzstd::frame_decoder::FrameDecoder>>` at /home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/mod.rs:424:19: 424:37
    = note: inside `std::io::default_read_to_end::<ruzstd::streaming_decoder::StreamingDecoder<&[u8], ruzstd::frame_decoder::FrameDecoder>>` at /home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/mod.rs:439:20: 439:44
    = note: inside `<ruzstd::streaming_decoder::StreamingDecoder<&[u8], ruzstd::frame_decoder::FrameDecoder> as std::io::Read>::read_to_end` at /home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/mod.rs:876:9: 876:45
```

The invoking code is not really special:
```
let mut uncompressed_file = <Vec<u8>>::new();
#[cfg(feature = "pure_rust_zstd")]
{
    let mut decoder =
        ruzstd::StreamingDecoder::new(&file[offset..offset + size])?;
    decoder.read_to_end(&mut uncompressed_file)?;
}
#[cfg(not(feature = "pure_rust_zstd"))]
{
    let mut dec = zstd::Decoder::new(&file[offset..offset + size])?;
    dec.read_to_end(&mut uncompressed_file)?;
    dec.finish();
}
```
where `offset` might be an arbitrary offset within a bigger buffer

### PR DESCRIPTION
**Pull request by paolobarbolini**
This fixes the unsoundness reported in #75 by correcting the `src` length math. Also adds safety and general comments, making it much easier to understand the logic.

The first commit fixes the vulnerability while the other commits cleanup the implementation and add two unrelated debug assertions.

Fixes #75

### CODE REVIEW

File: src/decoding/ringbuffer.rs [hunk 1]
```diff
@@ -301,7 +301,7 @@ impl RingBuffer {
             unsafe {
                 let src = (
                     self.buf.as_ptr().cast_const().add(self.head + start),
-                    self.tail - self.head,
+                    self.tail - self.head - start,
```
Comment (StarStarJ) [inline src/decoding/ringbuffer.rs:304]: So this reads like tail - `offset` similar to the line above `self.head + start`.. Maybe it should be made an extra var to be more clear for future readers?

File: src/decoding/ringbuffer.rs [hunk 2]
```diff
@@ -329,7 +329,7 @@ impl RingBuffer {
                 unsafe {
                     let src = (
                         self.buf.as_ptr().add(self.head + start).cast_const(),
-                        self.cap - self.head,
+                        self.cap - self.head - start,
```
Comment (StarStarJ) [inline src/decoding/ringbuffer.rs:332]: same here

**Review by StarStarJ — COMMENTED** [review]
Works for my workflow with this patch.

I don't know the code of this crate, so I cannot really help with a proper review.
But thanks for taking care :D

File: src/decoding/ringbuffer.rs [hunk 3]
```diff
@@ -296,49 +296,121 @@ impl RingBuffer {
...
-                    );
-                    let dst = (self.buf.as_ptr().add(self.tail), self.head - self.tail);
-                    copy_bytes_overshooting(src, dst, len);
-                }
+
+                let src = (
+                    // SAFETY: `len <= isize::MAX` and fits the memory range of `buf`
+                    unsafe { self.buf.as_ptr().add(start) }.cast_const(),
+                    // Src length (see above diagram)
+                    self.tail - start,
```
Comment (paolobarbolini) [inline src/decoding/ringbuffer.rs:357]: After adding comments I've realized this too was being miscalculated

**Comment by KillingSpark** [comment]
Thanks so much for fixing this!

The text comments do add a lot of claficiation. I find the diagrams a bit hard to read especially when they get to four lines of ^ markers.

Maybe something like this would be better?

```
|___HXXXSSSXXXXXXXTDD__|
H: Head position (first readable byte)
T: Tail position (first writeable byte)
X: Uninvolved bytes in the readable section
S: Source bytes, to be copied at the end of the buffer
D: Destination bytes, going to be written to by copying the source bytes
_: Uninvolved bytes in the writable section

|D__HXXXSSSSSSSXXXTDDDD|

|XXSSSSSXXXXXTDDDD__HXX|

|SSSXXTDDDD__HXXXXXXXSS|
```

**Comment by KillingSpark** [comment]
Yes! I thinks that's perfect

**Comment by paolobarbolini** [comment]
I think this is ready. I've tried adding Address Sanitizer and Memory Sanitizer to CI but they fail at linking:

```
test src/encoding/frame_encoder.rs - encoding::frame_encoder::FrameCompressor (line 44) ... FAILED
test src/frame_decoder.rs - frame_decoder::FrameDecoder (line 28) ... FAILED
```

**Comment by KillingSpark** [comment]
Thanks again for the quick action!
